print(f"      repo/")
print(f"      ├── indexmy")
print(f"      ├── favorites")
print(f"      ├── reading")
print(f"      ├── assess")
print(f"      │   ├── js")
print(f"      │   └── python")
print(f"      ├── objects")
print(f"      └── archive")
print(f"        └── beckoned")
